import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/About.module.css'
import TopBar from '../public/components/TopBar.tsx'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopBar />

      <div className={styles.background}>
        <div className={styles.foreground}>
          <div className = {styles.titleBck}>
            About Us
          </div>
          <div className = {styles.textBck} >
            The Save the World NFT project is a global initiative with the intent to fix what current politicians have failed to address. Currently, the world continues to get more and more polluted by the day, with little action on the part of politicians and corporations to mitigate the growing risks. Save the World NFT project intends to harness the power of the people through selling NFTs to obtain funds necessary to donate to parties which will assist in clearing the earth of pollution.
          </div>
        </div>
      </div> 

    </div>
  )
}
