import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import TopBar from '../public/components/TopBar.tsx'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopBar />
      <div className = {styles.backgroundImage}>
        <div className = {styles.saveContainer}>
          <h1 className = {styles.saveText}> 
            Save The
            <span className={styles.worldContainer}>
              <video className = {styles.textVideo} autoPlay loop >
                <source src="globe.mp4" type="video/mp4" />
              </video>
              <h1 className = {styles.saveText}>
                World.
              </h1>
            </span>
          </h1>
        </div>
      </div>
      <div className = {styles.backgroundUnder} >
        What?
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
