import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Roadmap.module.css'
import TopBar from '../public/components/TopBar.tsx'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopBar />

      <div className={styles.outerContainer} >
        <div className={styles.innerContainer} >
          <div className = {styles.titleContainer}>
            <h1 className={styles.titleText}> 
            <span>R</span>
            <span>O</span>
            <span>A</span>
            <span>D</span>
            <span>m</span>
            <span>A</span>
            <span>P</span></h1> 
          </div>
          <div className = {styles.contentContainer}>
            POW   
          </div>
        </div>
      </div>

    </div>
  )
}
